server:
 port: 8001

mybatis:
 config-location: classpath:mybatis/mybatis.cfg.xml
 type-aliases-package: com.dck.springcloud.entities
 mapper-location:
 - classpath:mybatis/mapper/**/*.xml
  
spring:
  application:
   name: microservicecloud-dept
  datasource:
   type: com.alibaba.druid.pool.DruidDataSource
   driverClassName: com.mysql.jdbc.Driver
   url: jdbc:mysql://localhost:3306/springcloud
   username: root
   password: root
   dbcp2: #启用dbcp2配置
     min-idle: 5 #最小空闲连接:连接池中容许保持空闲状态的最小连接数量,
     initial-size: 5 #初始化连接数量
     max-total: 5
     max-wait-millis: 200